CREATE TABLE Character (
    character_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_name VARCHAR2(50) NOT NULL,
    cha_level NUMBER,
    cha_class VARCHAR2(50),
    max_hp NUMBER,
    attact NUMBER,
    wisdom NUMBER,
    dexterity NUMBER,
    intelligence NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP
);

CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(255) NOT NULL,
    email VARCHAR2(45) NOT NULL UNIQUE,
    role VARCHAR2(45),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP,
    Character_character_id NUMBER,
    CONSTRAINT fk_user_char FOREIGN KEY (Character_character_id) REFERENCES Character(character_id)
);

CREATE TABLE Game_Room (
    room_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_password VARCHAR2(50),
    status VARCHAR2(20),
    room_name VARCHAR2(45),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Match (
    match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMP,
    current_turn NUMBER,
    room_id NUMBER,
    total_round NUMBER,
    CONSTRAINT fk_match_room FOREIGN KEY (room_id) REFERENCES Game_Room(room_id)
);

CREATE TABLE Map (
    map_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    map_name VARCHAR2(50),
    width NUMBER,
    height NUMBER,
    map_data CLOB,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleteAt TIMESTAMP,
    Match_match_id NUMBER,
    CONSTRAINT fk_map_match FOREIGN KEY (Match_match_id) REFERENCES Match(match_id)
);

CREATE TABLE Team (
    team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR2(50),
    match_id NUMBER,
    CONSTRAINT fk_team_match FOREIGN KEY (match_id) REFERENCES Match(match_id)
);

CREATE TABLE Game_Member (
    member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hp NUMBER,
    position_x NUMBER,
    position_y NUMBER,
    is_ready VARCHAR2(20),
    is_alive VARCHAR2(20),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id NUMBER,
    character_id NUMBER,
    team_id NUMBER,
    match_id NUMBER,
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES Users(user_id),
    CONSTRAINT fk_member_char FOREIGN KEY (character_id) REFERENCES Character(character_id),
    CONSTRAINT fk_member_team FOREIGN KEY (team_id) REFERENCES Team(team_id),
    CONSTRAINT fk_member_match FOREIGN KEY (match_id) REFERENCES Match(match_id)
);

CREATE TABLE Character_Item (
    character_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    character_id NUMBER,
    item_id NUMBER,
    quantity NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deletedAt TIMESTAMP,
    CONSTRAINT fk_charitem_char FOREIGN KEY (character_id) REFERENCES Character(character_id),
    CONSTRAINT fk_charitem_item FOREIGN KEY (item_id) REFERENCES Item(item_id)
);

CREATE TABLE Character_Skill (
    character_skill_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_id NUMBER,
    character_id NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_charskill_skill FOREIGN KEY (skill_id) REFERENCES Skill(skill_id),
    CONSTRAINT fk_charskill_char FOREIGN KEY (character_id) REFERENCES Character(character_id)
);

CREATE TABLE Dice_Roll (
    dice_roll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER,
    member_id NUMBER,
    dice_result NUMBER,
    roll_purpose VARCHAR2(50),
    roll_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Match_match_id NUMBER,
    CONSTRAINT fk_diceroll_room FOREIGN KEY (room_id) REFERENCES Game_Room(room_id),
    CONSTRAINT fk_diceroll_member FOREIGN KEY (member_id) REFERENCES Game_Member(member_id),
    CONSTRAINT fk_diceroll_match FOREIGN KEY (Match_match_id) REFERENCES Match(match_id)
);

CREATE TABLE Chat_Message (
    message_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER,
    member_id NUMBER,
    message VARCHAR2(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    match_id NUMBER,
    CONSTRAINT fk_chat_room FOREIGN KEY (room_id) REFERENCES Game_Room(room_id),
    CONSTRAINT fk_chat_member FOREIGN KEY (member_id) REFERENCES Game_Member(member_id),
    CONSTRAINT fk_chat_match FOREIGN KEY (match_id) REFERENCES Match(match_id)
);

CREATE TABLE Combat_Log (
    combat_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    damage_dealt NUMBER,
    turn_number NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    attacker_member_id NUMBER,
    target_member_id NUMBER,
    room_id NUMBER,
    skill_id NUMBER,
    dice_roll_id NUMBER,
    match_id NUMBER,
    CONSTRAINT fk_combat_att FOREIGN KEY (attacker_member_id) REFERENCES Game_Member(member_id),
    CONSTRAINT fk_combat_target FOREIGN KEY (target_member_id) REFERENCES Game_Member(member_id),
    CONSTRAINT fk_combat_room FOREIGN KEY (room_id) REFERENCES Game_Room(room_id),
    CONSTRAINT fk_combat_skill FOREIGN KEY (skill_id) REFERENCES Skill(skill_id),
    CONSTRAINT fk_combat_dice FOREIGN KEY (dice_roll_id) REFERENCES Dice_Roll(dice_roll_id),
    CONSTRAINT fk_combat_match FOREIGN KEY (match_id) REFERENCES Match(match_id)
);

CREATE TABLE Game_Result (
    result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id NUMBER,
    member_id NUMBER,
    result NUMBER,
    total_damage NUMBER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    match_id NUMBER,
    CONSTRAINT fk_result_room FOREIGN KEY (room_id) REFERENCES Game_Room(room_id),
    CONSTRAINT fk_result_member FOREIGN KEY (member_id) REFERENCES Game_Member(member_id),
    CONSTRAINT fk_result_match FOREIGN KEY (match_id) REFERENCES Match(match_id)
);